name: CI/CD Pipeline

on: [push]

jobs:
  format:
    name: Format code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install black

      - name: Run Black and apply formatting
        run: |
          black .

      - name: Commit formatted code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Autoformat with Black"
          git push || echo "No changes to push or push failed"

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests from tests/
        run: |
          python -m unittest discover -s tests

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Simulate deploy
        run: echo "Deploying the app (можно заменить на реальный скрипт)"
